### ISSUE TITLE
Script no longer working

### ISSUE THREAD

**Issue by theavidindoorsman** [mathiasxx/spinget#1]
Looks like Spinitron changed the location of their file storage. Your script is looking for the files at "https://ark-wxox.s3.us-east-1.amazonaws.com/" and the new location is "https://ark2.spinitron.com/ark2/".  I changed the location in your script to the new location, but that didn't fix the issue. I'm still getting 404 errors.

**Comment by mathiasxx** [comment]
Hmm, I see. There is even a nice m3u8 index file now.  Script is broken until further notice!

**Comment by theavidindoorsman** [comment]
Normally, a nice m3u8 file would be appreciated. You can use something like JDownloader to download the file inside the m3u8 for you or simply paste the link inside the m3u8 into a new tab and download it there. However, in this case, the link you get doesn't contain an ending time, only a starting time. Therefore, you end up getting the whole rest of the 24 hour period instead of what you actually wanted. Like in my case, I simply want the downloads of my 60 minute show.

**Comment by mathiasxx** [comment]
I played with it for a little today and made a little progress.  There appear to be index files for every 1/2 hour period.  So I've tired using those to get all the audio segments. However, when I concatenate them I get an mpeg (not what the format is actually...) that claims to be only 1/2 as long as it should be.  At least when I try to get my show, I attempt a one hour show, get 360 10s segments but the ultimate file reports 30min lengh in the player (where player is just the finder on my mac).  

Possibly there is some meta data I need to adjust?  

Feel free to play with it. The branch is mk-m3u8

**Comment by mathiasxx** [comment]
Using ffmpeg on the chunks works better, eg:

First of all set program to not delete all the chunks, then

`ls -1 wxox_0*.mpeg | awk '{print "file " $1}' >mylist.txt`
`ffmpeg -f concat -safe 0 -i mylist.txt -c copy outout.mpeg`

**Comment by mathiasxx** [comment]
I put the ffmpeg stuff in the script. I think it's working now.

**Comment by theavidindoorsman** [comment]
That's great. Thanks for keeping up with this. I'll give it a shot.

**Comment by theavidindoorsman** [comment]
I just tried it, but am getting a new error about SSL certs and such.
% ./spinget.py 01/25/2022 17:00 1
show start is 20220125T220000Z
fetching index for 20220125T220000Z
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sean/Downloads/spinget-main/./spinget.py", line 151, in <module>
    seglist = loadsegs(utcs, hours)
  File "/Users/sean/Downloads/spinget-main/./spinget.py", line 110, in loadsegs
    playlist = m3u8.load(INDEXURL.format(showtime))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/m3u8/__init__.py", line 46, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/m3u8/httpclient.py", line 20, in download
    resource = opener.open(uri, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by mathiasxx** [comment]
hmm, see this:
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by theavidindoorsman** [comment]
Good call. I dug into that thread and ran the install_certificates.command command. Certifi was installed and created the symlink to the certs. After that, the script ran fine. Thanks for the help. This probably wouldn't have happened on Windows. That thread seemed to be solely about Macs, which obviously I'm using.

**Comment by mathiasxx** [comment]
Excellent

**Comment by theavidindoorsman** [comment]
After working for one week, now I'm getting a new error. I decided to try and update ffmpeg to the latest version. Couldn't do that out of the gate, because I'm on a M1 Mac, so I had to to reinstall Homebrew and ffmpeg. Still didn't fix the issue. The script works up to the ffmpeg part and then ffmpeg can't concat the files. Since I already had the files downloaded, I simply took your commands out of this convo and ran them manually. Same error. I suspect the second error is because of the first, but not sure.

[mpegts @ 0x144e0b4d0] start time for stream 1 is not set in estimate_timings_from_pts
Input #0, concat, from 'wxox_20220201T220000Z_1h.mpeg.index':
  Duration: N/A, start: 0.000000, bitrate: 131 kb/s
  Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
  Stream #0:1: Data: timed_id3 (ID3  / 0x20334449)
[mpeg @ 0x144e0fb30] Unsupported audio codec. Must be one of mp1, mp2, mp3, 16-bit pcm_dvd, pcm_s16be, ac3 or dts.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times

**Comment by theavidindoorsman** [comment]
Thought this might be a new show problem, not an old show problem, so I tried running the script again for a show in the past two weeks with the same result. A show that I had previously used this script to successfully download last week mind you. So something has changed again.

**Comment by mathiasxx** [comment]
Thanks for bringing this to my attention. I'll look into it!

**Comment by mathiasxx** [comment]
Ok, from what I can tell that error was just that ffmpeg did not want to put aac into a ".mpeg" file.  All I did was change the final output extension to mp4 and it seems to work again.  Note that on linux you need something like vlc to play back the file.
